FROM webhippie/minecraft-forge:36.2-arm@sha256:d82f0e995bbf711287481b879654d0b6eee78574e83a4af049c704af806c471e

VOLUME ["/var/lib/minecraft", "/etc/minecraft/override"]
EXPOSE 25565 25575 8123

ENV MINECRAFT_LEVEL_TYPE biomesoplenty

COPY ./overlay /
COPY ./client/overrides /usr/share/minecraft
COPY ./client/manifest.json /usr/share/minecraft
COPY ./client/modlist.html /usr/share/minecraft

RUN apt-get update && \
  apt-get install -y jq && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/* && \
  download-mods
