baseURL = "https://crafthippie.github.io/bromance/"
languageCode = "en-us"
title = "Bromance"
disableKinds = ["taxonomy", "taxonomyTerm", "RSS", "sitemap"]

[blackfriday]
  angledQuotes = true
  fractions = false
  plainIDAnchors = true
  smartlists = true
  extensions = ["hardLineBreak"]

[params]
  author = "Thomas Boerger"
  description = "Documentation for Minecraft pack Bromance"
  keywords = "minecraft, mod, modpack, forge"
