---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yml
  - statefulset.yml

configMapGenerator:
  - name: minecraft-server
    options:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: server
    literals:
      - MINECRAFT_MOTD=Bromance by Webhippie

secretGenerator:
  - name: minecraft-server
    options:
      labels:
        app.kubernetes.io/name: minecraft
        app.kubernetes.io/component: server
    literals: []

images:
  - name: minecraft-server
    newName: quay.io/crafthippie/bromance
    newTag: 3.4.2@sha256:0212a6b4e614c940da6931f574280f349aeedf715d8db3eaecee4a8d766bc856

...
