---
name: docker

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout source
        id: source
        uses: actions/checkout@v2

      - name: Setup QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1

      - name: Setup Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Hub login
        id: login1
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Quay login
        id: login2
        uses: docker/login-action@v1
        if: github.event_name != 'pull_request'
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Meta amd64
        id: amd64
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            crafthippie/bromance
            quay.io/crafthippie/bromance
          labels: |
            org.opencontainers.image.vendor=Webhippie
            maintainer=Thomas Boerger <thomas@webhippie.de>
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            suffix=-amd64

      - name: Build amd64
        id: amd64
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.version.folder }}/
          file: ${{ matrix.version.folder }}/Dockerfile.amd64
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.amd64.outputs.labels }}
          tags: ${{ steps.amd64.outputs.tags }}

      - name: Meta arm64
        id: arm64
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            crafthippie/bromance
            quay.io/crafthippie/bromance
          labels: |
            org.opencontainers.image.vendor=Webhippie
            maintainer=Thomas Boerger <thomas@webhippie.de>
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            suffix=-arm64

      - name: Build arm64
        id: arm64
        uses: docker/build-push-action@v2
        if: matrix.version.arm64
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.version.folder }}/
          file: ${{ matrix.version.folder }}/Dockerfile.arm64
          platforms: linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.arm64.outputs.labels }}
          tags: ${{ steps.arm64.outputs.tags }}

      - name: Meta arm
        id: arm
        uses: docker/metadata-action@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          images: |
            crafthippie/bromance
            quay.io/crafthippie/bromance
          labels: |
            org.opencontainers.image.vendor=Webhippie
            maintainer=Thomas Boerger <thomas@webhippie.de>
          tags: |
            type=ref,event=pr
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/master' }}
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          flavor: |
            suffix=-arm

      - name: Build arm
        id: arm
        uses: docker/build-push-action@v2
        if: matrix.version.arm
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: ${{ matrix.version.folder }}/
          file: ${{ matrix.version.folder }}/Dockerfile.arm
          platforms: linux/arm/v7
          push: ${{ github.event_name != 'pull_request' }}
          labels: ${{ steps.arm.outputs.labels }}
          tags: ${{ steps.arm.outputs.tags }}

      - name: Hub manifest
        id: manifest1
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          template: crafthippie/bromance:${{ matrix.version.tag }}-ARCH
          target: crafthippie/bromance:${{ matrix.version.tag }}
          ignore_missing: true

      - name: Quay manifest
        id: manifest2
        uses: actionhippie/manifest@v1
        if: github.event_name != 'pull_request'
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          template: quay.io/crafthippie/bromance:${{ matrix.version.tag }}-ARCH
          target: quay.io/crafthippie/bromance:${{ matrix.version.tag }}
          ignore_missing: true

      - name: Hub readme
        uses: actionhippie/pushrm@v1
        if: github.event_name != 'pull_request'
        with:
          provider: dockerhub
          target: crafthippie/bromance
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          description: Docker image for ubuntu
          readme: README.md

      - name: Quay readme
        uses: actionhippie/pushrm@v1
        with:
          provider: quay
          target: quay.io/crafthippie/bromance
          apikey: ${{ secrets.QUAY_APIKEY }}
          readme: README.md

...
